#####
#Soubor: makefile
#Autor: Jan Wrona, xwrona00@stud.fit.vutbr.cz
#Datum: 02.05.2012
#Projekt: Projekt c. 2 pro predmet IOS
#####

NAME=proj2

preklad: $(NAME).c
	gcc -std=gnu99 -Wall -Wextra -Werror -pedantic -o readerWriter $(NAME).c -lrt -lpthread

clean: $(NAME).c
	rm readerWriter
